export const hashTb = {
  1: "Bảo hiểm",
  2: "Bất động sản",
  3: "Công nghệ",
  4: "Dầu khí",
  5: "Dịch vụ bán lẻ",
  6: "Dịch vụ tài chính",
  7: "Dịch vụ tiện ích",
  8: "Đồ dùng cá nhân và đồ gia dụng",
  9: "Du lịch & Giải trí",
  10: "Hàng hóa và dịch vụ công nghiệp",
  11: "Hóa chất",
  12: "Ngân hàng",
  13: "Ôtô & linh kiện phụ tùng ",
  14: "Phương tiện truyền thông",
  15: "Thực phẩm & Đồ uống",
  16: "Viễn thông",
  17: "Xây dựng & Vật liệu",
  18: "Tài nguyên",
  19: "Y tế",
  20: "Quỹ mở & quỹ đóng",
};
