export const hashTb = {
  "Bảo hiểm": "baoHiem",
  "Bất động sản": "batDongSan",
  "Công nghệ": "congNghe",
  "Dầu khí": "dauKhi",
  "Dịch vụ bán lẻ": "banLe",
  "Dịch vụ tài chính": "taiChinh",
  "Dịch vụ tiện ích": "tienIch",
  "Đồ dùng cá nhân và đồ gia dụng": "doGiaDung",
  "Du lịch & Giải trí": "duLich",
  "Hàng hóa và dịch vụ công nghiệp": "hangHoa",
  "Hóa chất": "hoaChat",
  "Ngân hàng": "nganHang",
  "Ôtô & linh kiện phụ tùng ": "oto",
  "Phương tiện truyền thông": "truyenThong",
  "Thực phẩm & Đồ uống": "thucPham",
  "Viễn thông": "vienThong",
  "Xây dựng & Vật liệu": "xayDung",
  "Tài nguyên": "taiNguyen",
  "Y tế": "yTe",
};
