export const stockType = {
    FETCH_DATA_INFO_HEADER: 'beta/FETCH_DATA_INFO_HEADER',
    FETCH_DATA_TABLE_TRANSACTION_STATISTICS: 'beta/FETCH_DATA_TABLE_TRANSACTION_STATISTICS',
    FETCH_DATA_FINANCIAL_INDICATORS: 'beta/FETCH_DATA_FINANCIAL_INDICATORS',
    FETCH_DATA_BUSINESS_RESULTS: 'beta/FETCH_DATA_BUSINESS_RESULTS',
    FETCH_DATA_BALANCE_SHEET: 'beta/FETCH_DATA_BALANCE_SHEET',
    FETCH_DATA_CASH_FLOW: 'beta/FETCH_DATA_CASH_FLOW',
    FETCH_DATA_SAME_INDUSTRY: 'beta/FETCH_DATA_SAME_INDUSTRY',
    FETCH_DATA_EVENTS: 'beta/FETCH_DATA_EVENTS',
    FETCH_DATA_TRANSACTION_DATA: 'beta/FETCH_DATA_TRANSACTION_DATA',
    FETCH_DATA_TRADING_PRICE_FLUCTUATIONS: 'beta/FETCH_DATA_TRADING_PRICE_FLUCTUATIONS',
    FETCH_DATA_AVERAGE_TRADING_VOLUME: 'beta/FETCH_DATA_AVERAGE_TRADING_VOLUME',
    FETCH_DATA_STATISTICS_BY_MONTH: 'beta/FETCH_DATA_STATISTICS_BY_MONTH',
    FETCH_DATA_STATISTICS_BY_QUARTER: 'beta/FETCH_DATA_STATISTICS_BY_QUARTER',
    FETCH_DATA_STATISTICS_BY_YEAR: 'beta/FETCH_DATA_STATISTICS_BY_YEAR'
}