export const stockType = {
  FETCH_DATA_INFO_HEADER: "beta/FETCH_DATA_INFO_HEADER",
  FETCH_DATA_TABLE_TRANSACTION_STATISTICS:
    "beta/FETCH_DATA_TABLE_TRANSACTION_STATISTICS",
  FETCH_DATA_FINANCIAL_INDICATORS: "beta/FETCH_DATA_FINANCIAL_INDICATORS",
  FETCH_DATA_BUSINESS_RESULTS: "beta/FETCH_DATA_BUSINESS_RESULTS",
  FETCH_DATA_BALANCE_SHEET: "beta/FETCH_DATA_BALANCE_SHEET",
  FETCH_DATA_CASH_FLOW: "beta/FETCH_DATA_CASH_FLOW",
  FETCH_DATA_SAME_INDUSTRY: "beta/FETCH_DATA_SAME_INDUSTRY",
  FETCH_DATA_EVENTS: "beta/FETCH_DATA_EVENTS",
  FETCH_DATA_TRANSACTION_DATA: "beta/FETCH_DATA_TRANSACTION_DATA",
  FETCH_DATA_TRADING_PRICE_FLUCTUATIONS:
    "beta/FETCH_DATA_TRADING_PRICE_FLUCTUATIONS",
  FETCH_DATA_AVERAGE_TRADING_VOLUME: "beta/FETCH_DATA_AVERAGE_TRADING_VOLUME",
  FETCH_DATA_STATISTICS_BY_MONTH: "beta/FETCH_DATA_STATISTICS_BY_MONTH",
  FETCH_DATA_STATISTICS_BY_QUARTER: "beta/FETCH_DATA_STATISTICS_BY_QUARTER",
  FETCH_DATA_STATISTICS_BY_YEAR: "beta/FETCH_DATA_STATISTICS_BY_YEAR",
  FETCH_DATA_TRADING_INVESTORS: "beta/FETCH_DATA_TRADING_INVESTORS",
  FETCH_DATA_NEWS_AND_EVENTS: "beta/FETCH_DATA_NEWS_AND_EVENTS",
  FETCH_DATA_NEWS: "beta/FETCH_DATA_NEWS",
  FETCH_DATA_TABLE_STATEMENTS_CASH_FLOWS:
    "beta/FETCH_DATA_TABLE_STATEMENTS_CASH_FLOWS",
  FETCH_DATA_CHART_STATEMENTS_CASH_FLOWS:
    "beta/FETCH_DATA_CHART_STATEMENTS_CASH_FLOWS",
  FETCH_DATA_CANDLE_CHART: "beta/FETCH_DATA_CANDLE_CHART",
  FETCH_DATA_INFO_HEADER_STATUS: "beta/FETCH_DATA_INFO_HEADER_STATUS",
  FETCH_DATA_TABLE_BUSINESS_REPORT: "beta/FETCH_DATA_TABLE_BUSINESS_REPORT",
  FETCH_DATA_CHART_BUSINESS_REPORT: "beta/FETCH_DATA_CHART_BUSINESS_REPORT",
  FETCH_DATA_TABLE_BALANCE_SHEET: "beta/FETCH_DATA_TABLE_BALANCE_SHEET",
  FETCH_DATA_CHART_BALANCE_SHEET: "beta/FETCH_DATA_CHART_BALANCE_SHEET",
  FETCH_DATA_CHART_PIE_BALANCE_SHEET: "beta/FETCH_DATA_CHART_PIE_BALANCE_SHEET",
  FETCH_DATA_TABLE_FINANCIAL_INDICATORS:
    "beta/FETCH_DATA_TABLE_FINANCIAL_INDICATORS",
  FETCH_DATA_CHART_FINANCIAL_INDICATORS:
    "beta/FETCH_DATA_CHART_FINANCIAL_INDICATORS",
  FETCH_DATA_FINANCIAL_HEALTH_ANALYSIS:
    "beta/FETCH_DATA_FINANCIAL_HEALTH_ANALYSIS",
  FETCH_DATA_FINANCIAL_HEALTH_ANALYSIS_STATUS:
    "beta/FETCH_DATA_FINANCIAL_HEALTH_ANALYSIS_STATUS",
  FETCH_DATA_BUSSINESS_ANALYSIS: "beta/FETCH_DATA_BUSSINESS_ANALYSIS",
  FETCH_DATA_BUSSINESS_ANALYSIS_STATUS:
    "beta/FETCH_DATA_BUSSINESS_ANALYSIS_STATUS",
  FETCH_DATA_BUSSINESS_POSITION: "beta/FETCH_DATA_BUSSINESS_POSITION",
  FETCH_DATA_BUSSINESS_POSITION_STATUS:
    "beta/FETCH_DATA_BUSSINESS_POSITION_STATUS",
  FETCH_DATA_BASIC_PRICE: "beta/FETCH_DATA_BASIC_PRICE",
  FETCH_DATA_BASIC_PRICE_STATUS: "beta/FETCH_DATA_BASIC_PRICE_STATUS",
  FETCH_DATA_TECHNICAL_ANALYSIS: "beta/FETCH_DATA_TECHNICAL_ANALYSIS",
  FETCH_DATA_TECHNICAL_ANALYSIS_STATUS:
    "beta/FETCH_DATA_TECHNICAL_ANALYSIS_STATUS",
  FETCH_DATA_INDIVIDUAL_INVESTOR_BENEFITS:
    "beta/FETCH_DATA_INDIVIDUAL_INVESTOR_BENEFITS",
  FETCH_DATA_INDIVIDUAL_INVESTOR_BENEFITS_STATUS:
    "beta/FETCH_DATA_INDIVIDUAL_INVESTOR_BENEFITS_STATUS",
  FETCH_DATA_RATING_HEADER: "beta/FETCH_DATA_RATING_HEADER",
  FETCH_DATA_FILTER_CANSLIM: "beta/FETCH_DATA_FILTER_CANSLIM",
  FETCH_DATA_TECHNICAL_INDEX: "beta/FETCH_DATA_TECHNICAL_INDEX",
  FETCH_DATA_INFO_STOCK: "beta/FETCH_DATA_INFO_STOCK",
  FETCH_DATA_PRICE_FLUCTUATION_CORRELATION:
    "beta/FETCH_DATA_PRICE_FLUCTUATION_CORRELATION",
  FETCH_DATA_PRICE_FLUCTUATION: "beta/FETCH_DATA_PRICE_FLUCTUATION",
  FETCH_DATA_SALES_ORDER_STATISTICS: "beta/FETCH_DATA_SALES_ORDER_STATISTICS",
  FETCH_DATA_HISTORICAL_PE_PB: "beta/FETCH_DATA_HISTORICAL_PE_PB",
};
