export const stockType = {
    FETCH_DATA_INFO_HEADER: 'beta/FETCH_DATA_INFO_HEADER',
    FETCH_DATA_TABLE_TRANSACTION_STATISTICS: 'beta/FETCH_DATA_TABLE_TRANSACTION_STATISTICS',
    FETCH_DATA_FINANCIAL_INDICATORS: 'beta/FETCH_DATA_FINANCIAL_INDICATORS'
}