export const optionsSelect = [
  { value: "cheBienGo", label: "SP Lâm nghiệp ( không tủ /bàn/ghế)" },
  { value: "cheBienKhac", label: "Chế biến/chế tạo khác" },
  { value: "det", label: "Sản phẩm dệt" },
  { value: "inSaoChep", label: "In ấn" },
  { value: "Da", label: "Sản xuất da" },
  { value: "doUong", label: "Đồ uống" },
  { value: "giay", label: "Công nghiệp giấy" },
  { value: "giuongTu", label: "Giường/ tủ / bàn ghế" },
  { value: "hoaChat", label: "Công nghiệp hóa chất" },
  { value: "kimLoai", label: "Kim loại" },
  { value: "mayMoc", label: "Máy/ thiết bị chưa phân loại" },
  { value: "vanTai", label: "Phương tiện vận tải" },
  { value: "dienTu", label: "Điện tử/ máy tính/quang học" },
  { value: "thuocLa", label: " Thuốc lá" },
  { value: "caoSu", label: "Cao su & Plastic" },
  { value: "phiKimLoai", label: "Khoáng phi kim" },
  { value: "kimLoaiDucSan", label: "Kim loại đúc sẵn" },
  { value: "than", label: "Than/dầu mỏ" },
  { value: "dien", label: "Thiết bị điện" },
  { value: "duocLieu", label: "Thuốc y tế" },
  { value: "trangPhuc", label: "Trang phục" },
  { value: "dongCo", label: "Sản xuất xe" },
  { value: "thucPham", label: "Thực phẩm" },
  { value: "all", label: "TOÀN NGÀNH" },
];

export const optionsSelect2 = [
  { value: "cheBienGo", label: "SP Lâm nghiệp ( không tủ /bàn/ghế)" },
  { value: "cheTao", label: "CN chế biến, chế tạo" },
  { value: "cheBienKhac", label: "Chế biến/chế tạo khác" },
  { value: "cungCapNuoc", label: "Dịch vụ hạ tầng" },
  { value: "det", label: "Sản phẩm dệt" },
  { value: "moQuang", label: "Khai khoáng" },
  { value: "rac", label: "Xử lý rác thải" },
  { value: "inSaoChep", label: "In ấn" },
  { value: "khaiKhoang", label: "Khai khoáng phi kim" },
  { value: "khaiKhoangKhac", label: "Khai khoáng khác" },
  { value: "dauTho", label: "Khai thác dầu mỏ" },
  { value: "quangKimLoai", label: "Khai khoáng kim loại" },
  { value: "than", label: "Khai thác than" },
  { value: "khaiThacNuoc", label: "Khai thác, cung cấp nước" },
  { value: "Da", label: "Sản xuất da" },
  { value: "doUong", label: "Đồ uống" },
  { value: "giay", label: "Công nghiệp giấy" },
  { value: "giuongTu", label: "Giường/ tủ / bàn ghế" },
  { value: "hoaChat", label: "Công nghiệp hóa chất" },
  { value: "kimLoai", label: "Kim loại" },
  { value: "mayMoc", label: "SX máy móc, thiết bị khác" },
  { value: "vanTai", label: "Phương tiện vận tải" },
  { value: "dienTu", label: "Điện tử/ máy tính/quang học" },
  { value: "thuocLa", label: "Thuốc lá" },
  { value: "caoSu", label: "Cao su & Plastic" },
  { value: "phiKimLoai", label: "Khoáng phi kim" },
  { value: "phiKimLoaiDucSan", label: "SX SP kim loại đúc sẵn" },
  { value: "thanCoc", label: "SX phụ phẩm dầu mỏ" },
  { value: "dien", label: "Thiết bị điện" },
  { value: "duocLieu", label: "Thuốc y tế" },
  { value: "trangPhuc", label: "Trang phục" },
  { value: "dieuHoa", label: "Sản xuất trang phục" },
  { value: "roMooc", label: "SX xe động cơ, rơ móc" },
  { value: "thucPham", label: "Thực phẩm" },
  { value: "baoDuong", label: "Bảo dưỡng, sửa chũa thiết bị" },
];

export const optionsSelect3 = [
  { value: "acQuyDienCacLoai", label: "Ắc quy (Nghìn kwh)" },
  { value: "baoBiVaTuiBangPlastic", label: "Bao bì/túi plastic (Nghìn tấn)" },
  { value: "baoInVaCacSanPhamInKhac", label: "In ấn (Tỷ trang)" },
  { value: "biaCacLoai", label: "Bia (Triệu lít)" },
  { value: "bongDenDien", label: "Bóng đèn (Triệu cái)" },
  {
    value: "botGiatVaCacChePhamDungDeTayRua",
    label: "Bột giặt,thuốc tẩy rửa (Nghìn tấn)",
  },
  { value: "botNgot", label: "Bột ngọt (Nghìn tấn)" },
  { value: "caPheBotVaCaPheHoaTan", label: "Cà phê bột & hòa tan (Nghìn tấn)" },
  { value: "catCacLoai", label: "Cát các loại* (Nghìn m3)" },
  { value: "cheCheBien", label: "Chè chế biến (Nghìn tấn)" },
  { value: "daKhaiThac", label: "Đá khai thác (Nghìn m3)" },
  { value: "dauGoiDauXa", label: "Dầu gội, dầu xả (Tấn)" },
  { value: "dauThoKhaiThac", label: "Dầu thô khai thác (Nghìn tấn)" },
  {
    value: "dauThoKhaiThacTrongNuoc",
    label: "Dầu thô KT trong nước (Nghìn tấn)",
  },
  {
    value: "dauThucVatTinhLuyen",
    label: "Dầu thực vật tinh luyện (Nghìn tấn)",
  },
  { value: "dienPhatRa", label: "Điện phát ra (Triệu Kwh)" },
  { value: "dienThoaiCoDinh", label: "Điện thoại cố định (Nghìn cái)" },
  { value: "dienThoaiDiDong", label: "Điện thoại di động (Triệu cái)" },
  { value: "duongKinh", label: "Đường kính (Nghìn tấn)" },
  { value: "gachNung", label: "Gạch nung (Triệu viên)" },
  { value: "gaoXayXat", label: "Gạo xay xát (Nghìn tấn)" },
  { value: "giayThethao", label: "Giày thể thao (Triệu đôi)" },
  { value: "giayVai", label: "Giày vải (Triệu đôi)" },
  { value: "giayBia", label: "Giấy, bìa (Nghìn tấn)" },
  { value: "giayDepDa", label: "Giày, dép da (Triệu đôi)" },
  { value: "goXe", label: "Gỗ xẻ (Nghìn m3)" },
  { value: "khiTuNhienODangKhi", label: "Khí tự nhiên (Triệu m3 )" },
  { value: "lopOtoMayKeoLoaiBomHoi", label: "Lốp ô tô (Nghìn cái)" },
  { value: "lopXeMayXeDapLoaiBomHoi", label: "Lốp xe máy, xe đạp (Nghìn cái)" },
  { value: "mayAnhKyThuatSo", label: "Máy ảnh (Nghìn cái)" },
  { value: "mayDieuHoaKhongKhi", label: "Máy điều hoà (Nghìn cái)" },
  { value: "mayGiatDungTrongGiaDinh", label: "Máy giặt (Nghìn cái)" },
  { value: "mayInCacLoai", label: "Máy in (Nghìn cái)" },
  { value: "mayTuotLua", label: "Máy tuốt lúa (Nghìn cái)" },
  { value: "muoiBien", label: "Muối biển (Nghìn tấn)" },
  { value: "ngoiNung", label: "Ngói nung (Triệu viên)" },
  { value: "nuocKhoang", label: "Nước khoáng (Triệu lít)" },
  { value: "nuocMam", label: "Nước mắm (Triệu lít)" },
  { value: "nuocMayThuongPham", label: "Nước máy (Triệu m3)" },
  { value: "nuocTinhKhiet", label: "Nước tinh khiết (Triệu lít)" },
  { value: "otoLapRap", label: "Ô tô lắp ráp (Nghìn cái)" },
  { value: "phanHoaHoc", label: "Phân hóa học (Nghìn tấn)" },
  { value: "phanNPK", label: "Phân NPK (Nghìn tấn)" },
  { value: "photPhoVang", label: "Phốt pho vàng (Tấn)" },
  { value: "pinQuyChuan15V", label: "Pin quy chuẩn (Triệu viên)" },
  { value: "quaVaHatDongHop", label: "Quả và hạt đóng hộp (Nghìn tấn)" },
  { value: "quanAoMacThuong", label: "Quần áo mặc thường (Triệu cái)" },
  {
    value: "quangAntimoanVaTinhQuangAntimoan",
    label: "Quặng antimoan và tinh quặng (Tấn)",
  },
  { value: "quangApatit", label: "Quặng apatít (Nghìn tấn)" },
  {
    value: "quangDongVaTinhQuangDong",
    label: "Quặng đồng và tinh quặng (Tấn)",
  },
  {
    value: "quangSatVaTinhQuangSat",
    label: "Quặng sắt và tinh quặng (Nghìn tấn)",
  },
  {
    value: "quangTitanVaTinhQuangTitan",
    label: "Titan & tinh quàng (Nghìn tấn)",
  },
  {
    value: "quatDienDungTrongGiaDinh",
    label: "Quạt điện dùng trong GD (Nghìn cái)",
  },
  { value: "rauDongHop", label: "Rau đóng hộp (Tấn)" },
  { value: "ruouManhVaRuouTrang", label: "Rượu (Triệu lít)" },
  { value: "samDungChoOtoMayBay", label: "Săm ô tô, máy bay (Nghìn cái)" },
  { value: "samDungChoXeDapXeMay", label: "Săm xe đạp, xe máy (Nghìn cái)" },
  {
    value: "satThepDangThoiDucHoacDangThoKhac",
    label: "Sắt, thép thỏi (Nghìn tấn)",
  },
  { value: "soi", label: "Sợi (Nghìn tấn)" },
  { value: "soiDaCuoi", label: "Sỏi, đá cuội (Nghìn m3)" },
  { value: "suDanDung", label: "Sứ dân dụng (Triệu cái)" },
  { value: "suVeSinh", label: "Sứ vệ sinh (Nghìn cái)" },
  { value: "suaBot", label: "Sữa bột (Nghìn tấn)" },
  { value: "suaTamSuaRuaMat", label: "Sữa tắm, sữa rửa mặt (Tấn)" },
  { value: "suaTuoi", label: "Sữa tươi (Triệu lít)" },
  { value: "tamLopFiproXiMang", label: "Fipro xi-măng (Triệu m2)" },
  { value: "thanSach", label: "Than sạch (Nghìn tấn)" },
  { value: "thepCanVaThepHinh", label: "Thép cán, thép hình (Nghìn tấn)" },
  { value: "thitHop", label: "Thịt hộp (Tấn)" },
  {
    value: "thucAnChoGiaSucVaGiaCam",
    label: "Thức ăn gia súc, gia cầm (Nghìn tấn)",
  },
  { value: "thucAnChoThuySan", label: "Thức ăn thủy sản (Nghìn tấn)" },
  { value: "thuocDanhRang", label: "Thuốc đánh răng (Tấn)" },
  { value: "thuocDietCo", label: "Thuốc diệt cỏ (Tấn)" },
  { value: "thuocLa", label: "Thuốc lá (Triệu bao)" },
  { value: "thuocTruSau", label: "Thuốc trừ sâu (Tấn)" },
  { value: "thuySanDongHop", label: "Thủy sản đóng hộp (Tấn)" },
  { value: "thuySanUopDong", label: "Thủy sản ướp đông (Nghìn tấn)" },
  { value: "tiViLapRap", label: "Ti vi (Nghìn cái)" },
  {
    value: "tuLanhVaTuDongDungTrongGiaDinh",
    label: "Tủ lạnh và tủ đông (Nghìn cái)",
  },
  { value: "vai", label: "Vải (Triệum2)" },
  { value: "xeDapCacLoai", label: "Xe đạp các loại (Nghìn cái)" },
  { value: "xeMoToXeMayLapRap", label: "Xe mô tô, xe máy (Nghìn cái)" },
  { value: "xiMang", label: "Xi măng (Nghìn tấn)" },
];
