export const optionsSelect = [
    { value: 'cheBienGo', label: 'Chế biến gỗ và sản xuất sản phẩm từ gỗ, tre, nứa (trừ giường, tủ, bàn ghế); sản xuất sản phẩm từ rơm, rạ và vật liệu tết bện' },
    { value: 'cheBienKhac', label: 'Công nghiệp chế biến, chế tạo khác' },
    { value: 'det', label: 'Dệt' },
    { value: 'inSaoChep', label: 'In, sao chép bản ghi các loại' },
    { value: 'Da', label: 'Sản xuất da và các sản phẩm có liên quan' },
    { value: 'doUong', label: 'Sản xuất đồ uống' },
    { value: 'giay', label: 'Sản xuất giấy và sản phẩm từ giấy' },
    { value: 'giuongTu', label: 'Sản xuất giường, tủ, bàn, ghế' },
    { value: 'hoaChat', label: 'Sản xuất hoá chất và sản phẩm hoá chất' },
    { value: 'kimLoai', label: 'Sản xuất kim loại' },
    { value: 'mayMoc', label: 'Sản xuất máy móc, thiết bị chưa được phân vào đâu' },
    { value: 'vanTai', label: 'Sản xuất phương tiện vận tải khác' },
    { value: 'dienTu', label: 'Sản xuất sản phẩm điện tử, máy vi tính và sản phẩm quang học' },
    { value: 'thuocLa', label: 'Sản xuất sản phẩm thuốc lá' },
    { value: 'caoSu', label: 'Sản xuất sản phẩm từ cao su và plastic' },
    { value: 'phiKimLoai', label: 'Sản xuất sản phẩm từ khoáng phi kim loại khác' },
    { value: 'kimLoaiDucSan', label: 'Sản xuất sản phẩm từ kim loại đúc sẵn (trừ máy móc, thiết bị)' },
    { value: 'than', label: 'Sản xuất than cốc, sản phẩm dầu mỏ tinh chế' },
    { value: 'dien', label: 'Sản xuất thiết bị điện' },
    { value: 'duocLieu', label: 'Sản xuất thuốc, hoá dược và dược liệu' },
    { value: 'trangPhuc', label: 'Sản xuất trang phục' },
    { value: 'dongCo', label: 'Sản xuất xe có động cơ, rơ moóc' },
    { value: 'thucPham', label: 'Sản xuất, chế biến thực phẩm' },
    { value: 'all', label: 'TOÀN NGÀNH CHẾ BIẾN, CHẾ TẠO' },
]

export const optionsSelect2 = [
    { value: 'cheBienGo', label: 'Chế biến gỗ và sản xuất sản phẩm từ gỗ, tre, nứa (trừ giường, tủ, bàn ghế); sản xuất sản phẩm từ rơm, rạ và vật liệu tết bện' },
    { value: 'cheTao', label: 'Công nghiệp chế biến, chế tạo' },
    { value: 'cheBienKhac', label: 'Công nghiệp chế biến, chế tạo khác' },
    { value: 'cungCapNuoc', label: 'Cung cấp nước; hoạt động quản lý và xử lý rác thải, nước thải' },
    { value: 'det', label: 'Dệt' },
    { value: 'moQuang', label: 'Hoạt động dịch vụ hỗ trợ khai thác mỏ và quặng' },
    { value: 'rac', label: 'Hoạt động thu gom, xử lý và tiêu huỷ rác thải; tái chế phế liệu' },
    { value: 'inSaoChep', label: 'In, sao chép bản ghi các loại' },
    { value: 'khaiKhoang', label: 'Khai khoáng' },
    { value: 'khaiKhoangKhac', label: 'Khai khoáng khác' },
    { value: 'dauTho', label: 'Khai thác dầu thô và khí đốt tự nhiên' },
    { value: 'quangKimLoai', label: 'Khai thác quặng kim loại' },
    { value: 'than', label: 'Khai thác than cứng và than non' },
    { value: 'khaiThacNuoc', label: 'Khai thác, xử lý và cung cấp nước' },
    { value: 'Da', label: 'Sản xuất da và các sản phẩm có liên quan' },
    { value: 'doUong', label: 'Sản xuất đồ uống' },
    { value: 'giay', label: 'Sản xuất giấy và sản phẩm từ giấy' },
    { value: 'giuongTu', label: 'Sản xuất giường, tủ, bàn, ghế' },
    { value: 'hoaChat', label: 'Sản xuất hoá chất và sản phẩm hoá chất' },
    { value: 'kimLoai', label: 'Sản xuất kim loại' },
    { value: 'mayMoc', label: 'Sản xuất máy móc, thiết bị chưa được phân vào đâu' },
    { value: 'vanTai', label: 'Sản xuất phương tiện vận tải khác' },
    { value: 'dienTu', label: 'Sản xuất sản phẩm điện tử, máy vi tính và sản phẩm quang học' },
    { value: 'thuocLa', label: 'Sản xuất sản phẩm thuốc lá' },
    { value: 'caoSu', label: 'Sản xuất sản phẩm từ cao su và plastic' },
    { value: 'phiKimLoai', label: 'Sản xuất sản phẩm từ khoáng phi kim loại khác' },
    { value: 'phiKimLoaiDucSan', label: 'Sản xuất sản phẩm từ kim loại đúc sẵn (trừ máy móc, thiết bị)' },
    { value: 'thanCoc', label: 'Sản xuất than cốc, sản phẩm dầu mỏ tinh chế' },
    { value: 'dien', label: 'Sản xuất thiết bị điện' },
    { value: 'duocLieu', label: 'Sản xuất thuốc, hoá dược và dược liệu' },
    { value: 'tranhPhuc', label: 'Sản xuất trang phục' },
    { value: 'dieuHoa', label: 'Sản xuất và phân phối điện, khí đốt, nước nóng, hơi nước và điều hoà không khí' },
    { value: 'roMooc', label: 'Sản xuất xe có động cơ, rơ moóc' },
    { value: 'thucPham', label: 'Sản xuất, chế biến thực phẩm' },
    { value: 'baoDuong', label: 'Sửa chữa, bảo dưỡng và lắp đặt máy móc, thiết bị' },
]

export const optionsSelect3 = [
    { value: 'acQuyDienCacLoai', label: 'Ắc quy điện các loại (Nghìn kwh)' },
    { value: 'baoBiVaTuiBangPlastic', label: 'Bao bì và túi bằng plastic (Nghìn tấn)' },
    { value: 'baoInVaCacSanPhamInKhac', label: 'Báo in và các sản phẩm in khác (Tỷ trang)' },
    { value: 'biaCacLoai', label: 'Bia các loại (Triệu lít)' },
    { value: 'bongDenDien', label: 'Bóng đèn điện (Triệu cái)' },
    { value: 'botGiatVaCacChePhamDungDeTayRua', label: 'Bột giặt và các chế phẩm dùng để tẩy, rửa (Nghìn tấn)' },
    { value: 'botNgot', label: 'Bột ngọt (Nghìn tấn)' },
    { value: 'caPheBotVaCaPheHoaTan', label: 'Cà phê bột và cà phê hòa tan (Nghìn tấn)' },
    { value: 'catCacLoai', label: 'Cát các loại* (Nghìn m3)' },
    { value: 'cheCheBien', label: 'Chè chế biến (Nghìn tấn)' },
    { value: 'daKhaiThac', label: 'Đá khai thác (Nghìn m3)' },
    { value: 'dauGoiDauXa', label: 'Dầu gội, dầu xả (Tấn)' },
    { value: 'dauThoKhaiThac', label: 'Dầu thô khai thác (Nghìn tấn)' },
    { value: 'dauThoKhaiThacTrongNuoc', label: 'Dầu thô khai thác trong nước (Nghìn tấn)' },
    { value: 'dauThucVatTinhLuyen', label: 'Dầu thực vật tinh luyện (Nghìn tấn)' },
    { value: 'dienPhatRa', label: 'Điện phát ra (Triệu Kwh)' },
    { value: 'dienThoaiCoDinh', label: 'Điện thoại cố định (Nghìn cái)' },
    { value: 'dienThoaiDiDong', label: 'Điện thoại di động (Triệu cái)' },
    { value: 'duongKinh', label: 'Đường kính (Nghìn tấn)' },
    { value: 'gachNung', label: 'Gạch nung (Triệu viên)' },
    { value: 'gaoXayXat', label: 'Gạo xay xát (Nghìn tấn)' },
    { value: 'giayThethao', label: 'Giày thể thao (Triệu đôi)' },
    { value: 'giayVai', label: 'Giày vải (Triệu đôi)' },
    { value: 'giayBia', label: 'Giấy, bìa (Nghìn tấn)' },
    { value: 'giayDepDa', label: 'Giày, dép da (Triệu đôi)' },
    { value: 'goXe', label: 'Gỗ xẻ (Nghìn m3)' },
    { value: 'khiTuNhienODangKhi', label: 'Khí tự nhiên ở dạng khí (Triệu m3 )' },
    { value: 'lopOtoMayKeoLoaiBomHoi', label: 'Lốp ô tô, máy kéo loại bơm hơi (Nghìn cái)' },
    { value: 'lopXeMayXeDapLoaiBomHoi', label: 'Lốp xe máy, xe đạp loại bơm hơi (Nghìn cái)' },
    { value: 'mayAnhKyThuatSo', label: 'Máy ảnh kỹ thuật số (Nghìn cái)' },
    { value: 'mayDieuHoaKhongKhi', label: 'Máy điều hoà không khí (Nghìn cái)' },
    { value: 'mayGiatDungTrongGiaDinh', label: 'Máy giặt dùng trong gia đình (Nghìn cái)' },
    { value: 'mayInCacLoai', label: 'Máy in các loại (Nghìn cái)' },
    { value: 'mayTuotLua', label: 'Máy tuốt lúa (Nghìn cái)' },
    { value: 'muoiBien', label: 'Muối biển (Nghìn tấn)' },
    { value: 'ngoiNung', label: 'Ngói nung (Triệu viên)' },
    { value: 'nuocKhoang', label: 'Nước khoáng (Triệu lít)' },
    { value: 'nuocMam', label: 'Nước mắm (Triệu lít)' },
    { value: 'nuocMayThuongPham', label: 'Nước máy thương phẩm (Triệu m3)' },
    { value: 'nuocTinhKhiet', label: 'Nước tinh khiết (Triệu lít)' },
    { value: 'otoLapRap', label: 'Ô tô lắp ráp (Nghìn cái)' },
    { value: 'phanHoaHoc', label: 'Phân hóa học (Nghìn tấn)' },
    { value: 'phanNPK', label: 'Phân NPK (Nghìn tấn)' },
    { value: 'photPhoVang', label: 'Phốt pho vàng (Tấn)' },
    { value: 'pinQuyChuan15V', label: 'Pin quy chuẩn (1,5V) (Triệu viên)' },
    { value: 'quaVaHatDongHop', label: 'Quả và hạt đóng hộp (Nghìn tấn)' },
    { value: 'quanAoMacThuong', label: 'Quần áo mặc thường (Triệu cái)' },
    { value: 'quangAntimoanVaTinhQuangAntimoan', label: 'Quặng antimoan và tinh quặng antimoan (Tấn)' },
    { value: 'quangApatit', label: 'Quặng apatít (Nghìn tấn)' },
    { value: 'quangDongVaTinhQuangDong', label: 'Quặng đồng và tinh quặng đồng (Tấn)' },
    { value: 'quangSatVaTinhQuangSat', label: 'Quặng sắt và tinh quặng sắt (Nghìn tấn)' },
    { value: 'quangTitanVaTinhQuangTitan', label: 'Quặng Titan và tinh quàng Titan (Nghìn tấn)' },
    { value: 'quatDienDungTrongGiaDinh', label: 'Quạt điện dùng trong gia đình (Nghìn cái)' },
    { value: 'rauDongHop', label: 'Rau đóng hộp* (Tấn)' },
    { value: 'ruouManhVaRuouTrang', label: 'Rượu mạnh và rượu trắng (Triệu lít)' },
    { value: 'samDungChoOtoMayBay', label: 'Săm dùng cho ô tô, máy bay (Nghìn cái)' },
    { value: 'samDungChoXeDapXeMay', label: 'Săm dùng cho xe đạp, xe máy (Nghìn cái)' },
    { value: 'satThepDangThoiDucHoacDangThoKhac', label: 'Sắt, thép dạng thỏi đúc hoặc dạng thô khác (Nghìn tấn)' },
    { value: 'soi', label: 'Sợi (Nghìn tấn)' },
    { value: 'soiDaCuoi', label: 'Sỏi, đá cuội (Nghìn m3)' },
    { value: 'suDanDung', label: 'Sứ dân dụng (Triệu cái)' },
    { value: 'suVeSinh', label: 'Sứ vệ sinh (Nghìn cái)' },
    { value: 'suaBot', label: 'Sữa bột (Nghìn tấn)' },
    { value: 'suaTamSuaRuaMat', label: 'Sữa tắm, sữa rửa mặt (Tấn)' },
    { value: 'suaTuoi', label: 'Sữa tươi (Triệu lít)' },
    { value: 'tamLopFiproXiMang', label: 'Tấm lợp fipro xi-măng (Triệu m2)' },
    { value: 'thanSach', label: 'Than sạch (Nghìn tấn)' },
    { value: 'thepCanVaThepHinh', label: 'Thép cán và thép hình (Nghìn tấn)' },
    { value: 'thitHop', label: 'Thịt hộp (Tấn)' },
    { value: 'thucAnChoGiaSucVaGiaCam', label: 'Thức ăn cho gia súc và gia cầm (Nghìn tấn)' },
    { value: 'thucAnChoThuySan', label: 'Thức ăn cho thủy sản (Nghìn tấn)' },
    { value: 'thuocDanhRang', label: 'Thuốc đánh răng (Tấn)' },
    { value: 'thuocDietCo', label: 'Thuốc diệt cỏ (Tấn)' },
    { value: 'thuocLa', label: 'Thuốc lá (Triệu bao)' },
    { value: 'thuocTruSau', label: 'Thuốc trừ sâu (Tấn)' },
    { value: 'thuySanDongHop', label: 'Thủy sản đóng hộp (Tấn)' },
    { value: 'thuySanUopDong', label: 'Thủy sản ướp đông (Nghìn tấn)' },
    { value: 'tiViLapRap', label: 'Ti vi lắp ráp (Nghìn cái)' },
    { value: 'tuLanhVaTuDongDungTrongGiaDinh', label: 'Tủ lạnh và tủ đông dùng trong gia đình (Nghìn cái)' },
    { value: 'vai', label: 'Vải (Triệum2)' },
    { value: 'xeDapCacLoai', label: 'Xe đạp các loại (Nghìn cái)' },
    { value: 'xeMoToXeMayLapRap', label: 'Xe mô tô, xe máy lắp ráp (Nghìn cái)' },
    { value: 'xiMang', label: 'Xi măng (Nghìn tấn)' },
]