export const investToolType = {
    FETCH_DATA_RANGE_MIN_MAX: 'beta/FETCH_DATA_RANGE_MIN_MAX',
    FETCH_DATA_STOCK_FILTER: 'beta/FETCH_DATA_STOCK_FILTER',
    FETCH_DATA_STOCK_LIST: 'beta/FETCH_DATA_STOCK_LIST'
}