export const macroType = {
    FETCH_DATA_GDP_BY_INDUSTRY: 'beta/FETCH_DATA_GDP_BY_INDUSTRY',
    FETCH_DATA_GDP_BY_PRICE: 'beta/FETCH_DATA_GDP_BY_PRICE',
    FETCH_DATA_GDP_CONTRIBUTION_RATIO: 'beta/FETCH_DATA_GDP_CONTRIBUTION_RATIO',
    FETCH_DATA_GDP_GROWTH: 'beta/FETCH_DATA_GDP_GROWTH',
    FETCH_DATA_PER_GDP_GROWTH: 'beta/FETCH_DATA_PER_GDP_GROWTH',
}