export const marketType = {
    FETCH_DATA_TABLE_THANH_KHOAN: 'beta/FETCH_DATA_TABLE_THANH_KHOAN',
    FETCH_DATA_CHART_TICKER_CONTRIBUTE: 'beta/FETCH_DATA_CHART_TICKER_CONTRIBUTE',
    FETCH_DATA_LINE_CHART_MARKET: 'beta/FETCH_DATA_LINE_CHART_MARKET',
    FETCH_DATA_INVESTOR_TRANSACTION: 'beta/FETCH_DATA_INVESTOR_TRANSACTION',
    FETCH_DATA_CASH_VALUE: 'beta/FETCH_DATA_CASH_VALUE'
}