export const newsCenterType = {
    FETCH_DATA_TABLE_EVENTS: 'beta/FETCH_DATA_TABLE_EVENTS',
    FETCH_NEWS_TOOL: 'beta/FETCH_NEWS_TOOL',
    FETCH_DATA_DOMESTIC_MARCO: 'beta/FETCH_DATA_DOMESTIC_MARCO',
    FETCH_DATA_FOREIGN_MARCO: 'beta/FETCH_DATA_FOREIGN_MARCO',
    FETCH_DATA_LIST_ENTERPRISE_NEWS: 'beta/FETCH_DATA_LIST_ENTERPRISE_NEWS',
    FETCH_DATA_STOCK_INFO: 'beta/FETCH_DATA_STOCK_INFO',
    FETCH_DATA_NEWS_FILTER: 'beta/FETCH_DATA_NEWS_FILTER'

}