export const newsCenterType = {
    FETCH_DATA_TABLE_EVENTS: 'beta/FETCH_DATA_TABLE_EVENTS',
    FETCH_DATA_DOMESTIC_MARCO: 'beta/FETCH_DATA_DOMESTIC_MARCO',
    FETCH_DATA_LIST_ENTERPRISE_NEWS: 'beta/FETCH_DATA_LIST_ENTERPRISE_NEWS',
}